### ISSUE TITLE
installer doesn't work on debian 

### ISSUE THREAD

**Issue by LeOS-GSI** [Nerun/remastersys#7]
Hi, first of all: thx for the latest update, autologin is now working on debian :)) 

But now I faced the next issue. The installer doesn't work, not with gui or terminal. With gui from start menu, nothing happens. When using `sudo remastersys install` only the help text appears

**Comment by nerun** [comment]
Thank you for your feedback, i will take a look!

**Comment by nerun** [comment]
@LeOS-GSI, i have remembered one known bug. When you run `sudo` in your machine, it ask for password? Because installer need sudo, but GUI doesn't ask for sudo password, so nothing happens. When you remove the need for password in `sudo visudo` it works. Could you verify this when you have some time? If this is the problem i can fix by adding a screen asking for sudo password.

**Comment by LeOS-GSI** [comment]
mhm, I'm always using terminal and running `sudo remastersys install` and that doesn't work. It only shows the remastersys help scree.

But I can try on weekend with removed root pw

**Comment by LeOS-GSI** [comment]
OK, after remove the root PW the gui installer is working. Thx again

**Comment by nerun** [comment]
Thank you! Working on it.

## NOTE TO MYSELF:

I am scripting a `yad-sudo` command to be used in desktop shortcuts and menu entries.

Currently menus execute  `sudo remastersys-installer --gui`. That's why nothing happens. Sudo is a terminal command. When used to start any GUI application the user doesn't see the "enter password". This bug happens with all the other remastersys menu entries.

New menu will execute `yad-sudo remastersys-installer --gui` instead. Yad-sudo will open a GUI to enter password and print it to _stdout_ then send password immediately to `sudo -S remastersys-installer --gui` (_without_ store password in a variable or a file). In addition, script will verify if $USER is the same as $LIVEUSER, if yes the yad-sudo will not ask for password because the LIVEUSER password is always equals to LIVEUSER name. So yad-sudo don't need to ask and can print default password to stdout immediately.

## NOTE 2:
Some scripts should work only if executed from a Live CD. Specially remastersys-installer. So i need to add a verification if running from live cd or not.

**Comment by nerun** [comment]
@LeOS-GSI just to you know, commit 2cc94d2 apparently have fixed this issue. Please, try when you can.

Thank you for all your contribution.
